training_pipeline_config:
  pipeline_name: banking_analysis_artifact
  artifact_dir: artifact

data_ingestion_config: 
  dataset_download_url: https://raw.githubusercontent.com/GeetaKeote/Datasets/main/Banking_term_deposit%20Analysis.csv
  ingested_dir: ingested_Data
  raw_data_dir: raw_data
  ingested_train_dir: train
  ingested_test_dir: test
